Hostコードにlints check導入
LayerXcom/anonify pull request #599
Opened 2021-05-22 10:48 UTC by osuketh

## Issueへのリンク

* 

## やったこと

* Hostコードに対して、`cargo fmt/clippy` の適用
* CIにlints check追加

## やらないこと

* Enclaveコードのlints

## 動作検証

* CI check

## 参考

*

2021-05-22 10:52 UTC, laysakura requested changes

2021-05-22 10:52 UTC, laysakura commented on scripts/test.sh
> +cargo clippy -p erc20-server -p key-vault-server --all-targets --all-features -- -D warnings
`-- -D warnings` ってやると clippy warning も引っ掛けてくれるように思えるんですが、実際には

```suggestion
`RUSTFLAGS='-D warnings'  cargo clippy -p erc20-server -p key-vault-server --all-targets --all-features
```

ってやらないと拾えないのを別プロジェクトで確認済みです 🙄

2021-05-22 11:01 UTC, osuketh commented on scripts/test.sh
> +cargo clippy -p erc20-server -p key-vault-server --all-targets --all-features -- -D warnings
おおあざます！！

2021-05-23 09:12 UTC, osuketh reviewed
fixed

2021-05-23 09:44 UTC, cipepser approved these changes

2021-05-23 10:46 UTC, laysakura approved these changes
🙌

2021-05-23 10:49 UTC, merged