Feature/encrypted avg sql roadmap4
LayerXcom/anonify pull request #621
Opened 2021-05-27 12:15 UTC by laysakura

## Issueへのリンク

* https://github.com/LayerXcom/anonify/issues/xxx

## やったこと

* このプルリクで何をしたのか？

## やらないこと

* このプルリクでやらないことは何か？(あれば、無いなら「無し」でOK)(やらない場合は、該当Issueへのリンクを明記する)

## 動作検証

* どのような動作確認を行ったのか？結果はどうか？

## 参考

* レビュワーへの参考情報(実装上の懸念点や注意点などあれば記載)

2021-06-03 16:27 UTC, osuketh requested changes

2021-06-03 16:27 UTC, osuketh commented on azure-pipelines.yml
> +  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
テスト方針、相談したい話なのですが、以下の理由で `example-encrypted-sql-ops-pg.Dockerfile`ではなく `base-anonify-dev-pgx.Dockerfile`  で現状の `scripts/test.sh` のようなテスト実行するのはいかがでしょうか。

* ソースコードのテスト実行はmain merge時じゃなくfeat branchでチェックしたい（docker build時のpkg installやらでより遅い）
* EnclaveのユニットテストもCIに入れたい（現状、prdビルドしている）
* CI実行時に、[本番環境のEnclave署名](https://github.com/LayerXcom/anonify/pull/621/files#diff-14a024630bd7f489ff898f9a3e273cbbd5c757af1bf87558a2ea83ce57b6ed8dR39)などをできるだけ実行したくない

2021-06-03 16:27 UTC, osuketh commented on example/encrypted-sql-ops/pg-extension/Cargo.toml
> +codegen-units = 1
このprofile必要なのかー
https://github.com/zombodb/pgx/blob/eec5e2f720236ede1eb2f106a8641623071d0ffa/pgx-examples/strings/Cargo.toml#L27

2021-06-03 16:27 UTC, osuketh commented on example/encrypted-sql-ops/pg-extension/src/func.rs
> +    EncAvgState::from(ModuleEncAvgState::from(host_output))
IMO: `.into()` したくなってしまう病

2021-06-03 22:20 UTC, laysakura commented on example/encrypted-sql-ops/pg-extension/.cargo/config
> +# Postgres symbols won't ve available until runtime
これpgx側のtypoで、自動生成されてる .cargo/config は全員食らってる 😇
https://github.com/zombodb/pgx/search?q=Postgres+symbols+won%27t+ve+available+until+runtime

直しておきます

2021-06-03 22:27 UTC, laysakura commented on example/encrypted-sql-ops/pg-extension/Cargo.toml
> +codegen-units = 1
example/encrypted-sql-ops/pg-extension を anonify の cargo workspace member から外しているので、
cargo pgx new で自動生成されるファイルはなるべくそのままにしているという事情です。

example/encrypted-sql-ops/pg-extension をworkspaceの一員にしてしまうと、workspaceレベルでのcargo buildに `cargo install cargo-pgx` が事前に必要になってしまうため。

今回のコード差分のうち、 example/encrypted-sql-ops/pg-extension 以外は「PostgreSQL以外のRDBMSのエクステンションとしても使える」レベルの汎用性を意図して作っているので anonify リポジトリに残しておくのも妥当だと思っていますが、
example/encrypted-sql-ops/pg-extension は汎用性のないアプリなので別リポ開発のほうが何かと身軽な気が本当はしています 🤔 
（OKならこのPRマージ後, exit-mechanism 導入前にその作業します）

2021-06-03 22:38 UTC, laysakura commented on example/encrypted-sql-ops/pg-extension/src/func.rs
> +            eid, e
そうです！

https://github.com/zombodb/pgx#safety-first

> Translates Rust panic!s into Postgres ERRORs that abort the transaction, not the process

2021-06-03 22:38 UTC, laysakura commented on azure-pipelines.yml
> +  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
現在の[E2Eテスト](https://github.com/LayerXcom/anonify/pull/621/files#diff-356704499fb158fea975ae4fe35558ab64d6ba185f86750d1454448057555fc5R29-R52)は実際にecallを発行します。その場合に本番環境のEnclave署名を迂回する方法を自分は知らず... 🙄 

ユニットテストを 
> base-anonify-dev-pgx.Dockerfile で現状の scripts/test.sh 

はできるはずですし、何ならユニットテストは postgres 非依存のところにしか書いていないので `base-anonify-dev-pgx.Dockerfile` も使えそうです。

E2Eテストの実行方針について追加アドバイスいただけると嬉しいです 🙏

2021-06-03 22:54 UTC, laysakura commented on example/encrypted-sql-ops/pg-extension/src/func.rs
> +    f32::from(host_output)
e0953a

2021-06-03 22:56 UTC, laysakura commented on example/encrypted-sql-ops/pg-extension/src/func.rs
> +    EncAvgState::from(ModuleEncAvgState::from(host_output))
1c3f27

2021-06-04 00:33 UTC, laysakura commented on esop-docker-compose.yml
> +        USER=anonify-dev cargo pgx test pg13
workspace member に入ってるcrate については 06771c7 で追加しました。

anonify/example/encrypted-sql-ops/pg-extension については 1bd119f で追加しましたが、独立リポジトリにしてから fmt などと合わせてしっかり整備するのが吉かなと思っています。

2021-06-04 00:33 UTC, laysakura commented on example/encrypted-sql-ops/pg-extension/.cargo/config
> +# Postgres symbols won't ve available until runtime
6719f60

2021-06-04 00:38 UTC, laysakura commented on modules/encrypted-sql-ops-enclave/src/plain_types/plain_avg_state.rs
> +    fn test_calculation() {
a48b03f で追加したり、 `cargo build --tests` しないと気づかないコンパイルエラーの修正をしました。

ただ、 `cargo build --tests` の際に以下のエラーが出ています。

```
   Compiling module-encrypted-sql-ops-enclave v0.1.0 (/home/anonify-dev/anonify/modules/encrypted-sql-ops-enclave)
error: duplicate lang item in crate `std` (which `test` depends on): `f32_runtime`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `module_encrypted_sql_ops_enclave` depends on)
  = note: first definition in `sgx_tstd` loaded from /home/anonify-dev/anonify/target/debug/deps/libsgx_tstd-acbff3eee673f4ee.rlib
  = note: second definition in `std` loaded from /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.so, /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.rlib

error: duplicate lang item in crate `std` (which `test` depends on): `f64_runtime`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `module_encrypted_sql_ops_enclave` depends on)
  = note: first definition in `sgx_tstd` loaded from /home/anonify-dev/anonify/target/debug/deps/libsgx_tstd-acbff3eee673f4ee.rlib
  = note: second definition in `std` loaded from /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.so, /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.rlib

error: duplicate lang item in crate `std` (which `test` depends on): `panic_impl`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `module_encrypted_sql_ops_enclave` depends on)
  = note: first definition in `sgx_tstd` loaded from /home/anonify-dev/anonify/target/debug/deps/libsgx_tstd-acbff3eee673f4ee.rlib
  = note: second definition in `std` loaded from /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.so, /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.rlib

error: duplicate lang item in crate `std` (which `test` depends on): `begin_panic`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `module_encrypted_sql_ops_enclave` depends on)
  = note: first definition in `sgx_tstd` loaded from /home/anonify-dev/anonify/target/debug/deps/libsgx_tstd-acbff3eee673f4ee.rlib
  = note: second definition in `std` loaded from /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.so, /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.rlib

error: duplicate lang item in crate `std` (which `test` depends on): `oom`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `module_encrypted_sql_ops_enclave` depends on)
  = note: first definition in `sgx_tstd` loaded from /home/anonify-dev/anonify/target/debug/deps/libsgx_tstd-acbff3eee673f4ee.rlib
  = note: second definition in `std` loaded from /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.so, /home/anonify-dev/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.rlib

error: aborting due to 5 previous errors

error: could not compile `module-encrypted-sql-ops-enclave`
```

おそらく [ここのno_std指定](https://github.com/LayerXcom/anonify/pull/621/files#diff-069d2f81cbf9263c6340deb9ad3a97c7dad16a16950f11d1698513d383d85030R8) が間違っていると思うのですが、[key-vaultの方](https://github.com/LayerXcom/anonify/blob/main/modules/key-vault-enclave/src/lib.rs#L1)を真似した行なので、どうあるのが正しいか確認したいです 🙇

2021-06-04 00:50 UTC, laysakura commented on modules/encrypted-sql-ops-enclave/src/plain_types/plain_avg_state.rs
> +    fn test_calculation() {
別途回答頂いたので自己レス:

- `target_env = "sgx"` になるのは https://github.com/fortanix/rust-sgx を使った場合。
- このリポジトリにおいてもはや fortanix は使っていないので、無条件で `#![no_std]` でOK

2021-06-04 03:42 UTC, osuketh commented on azure-pipelines.yml
> +  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
> 本番環境のEnclave署名を迂回する方法
makefileで[prd-signed.soをビルド](https://github.com/LayerXcom/anonify/blob/6107d33769433b1d0df50d07732a53bd21a360b1/scripts/Makefile#L155)するのではなく、[`$(Signed_Enclave_SO)`をビルド](https://github.com/LayerXcom/anonify/blob/6107d33769433b1d0df50d07732a53bd21a360b1/scripts/Makefile#L149)すると回避できます。
key-vaultだと[こんな感じでmake](https://github.com/LayerXcom/anonify/blob/6107d33769433b1d0df50d07732a53bd21a360b1/scripts/test.sh#L43-L44)してます。

2021-06-04 03:52 UTC, osuketh commented on example/encrypted-sql-ops/pg-extension/Cargo.toml
> +codegen-units = 1
> workspaceレベルでのcargo buildに cargo install cargo-pgx が事前に必要になってしまうため。

workspaceレベルでcargo buildすると sgx/stdが混ざってしまうのでビルドすることはないと思うのですが、rust-analyzer的な事情ですかね？

> example/encrypted-sql-ops/pg-extension は汎用性のないアプリなので別リポ開発のほうが何かと身軽な気が本当はしています

exampleレイヤ開発していると結局frameやmoduleも色々修正したくなり、anonifyにpushしてcargo updateして.. は今の色々いじるフェーズだと少し手間かかりそうなので少なくともある程度fixするまではここで進めて良きかな〜と思います。

2021-06-04 03:57 UTC, laysakura commented on modules/encrypted-sql-ops-enclave/src/plain_types/plain_avg_state.rs
> +    fn test_calculation() {
紆余曲折あったが 30e5fffb9db515f808674663b9fed6ce5c1bca19 でなんとかユニットテスト追加

2021-06-04 04:03 UTC, laysakura commented on example/encrypted-sql-ops/pg-extension/Cargo.toml
> +codegen-units = 1
> rust-analyzer的な事情

そうです。

> workspaceレベルでcargo buildすると sgx/stdが混ざってしまうので元々ビルドすることはない

これはたしかにそうですね。しかしworkspaceレベルでのcargo xxx はできるようにしておかないと、今の test.sh のように細かく `-p crate名` とかしてclippyやfmtを当てていくことになる（crate追加の際に忘れやすい）のが懸念です。
1リポジトリに複数workspaceでも行けると思うので、workspaceレベルで cargo xxx できるようにre-structureしていくのはやっていきたいです（このPRとは別に）。

> exampleレイヤ開発していると結局frameやmoduleも色々修正したくなり、anonifyにpushしてcargo updateして.. は今の色々いじるフェーズだと少し手間かかりそうなので少なくともある程度fixするまではここで進めて良きかな〜と思います。

なるほど同意 x 100です。ここに残しておきます！

2021-06-04 04:29 UTC, laysakura commented on esop-docker-compose.yml
> +        USER=anonify-dev cargo pgx test pg13
clippy target 広いと（ --all-features にしていることもあり）コンパイルエラーになってしまうので、 4c39f3f7ca4efa3f3802a1bb0eb58d37fd712a46 にて狭めました... 😞 

clippy 入れた結果出たエラーは 46aa090e08216764234e2cbbfe2b4e795cf58de4 で修正してます。

2021-06-04 04:52 UTC, laysakura commented on azure-pipelines.yml
> +  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
最終的に目指す形が同じか自信がないので、イメージを箇条書きにさせてください。

- example-encrypted-sql-ops-pg.Dockerfile
  - 削除。他のE2Eのように、コンテナを立てて外部からHTTPで叩くような使い方はしないので。
- modules/encrypted-sql-ops-enclave のユニットテスト
  - https://github.com/LayerXcom/anonify/pull/621#discussion_r645272523 で話した状態。つまり test.sh にてkick。pgx不要なので。
- 現在の[E2Eテスト](https://github.com/LayerXcom/anonify/pull/621/files#diff-356704499fb158fea975ae4fe35558ab64d6ba185f86750d1454448057555fc5R29-R52)
  - test-pg-extension.sh のような新設スクリプトからkick。このスクリプトは azure-pipelines.yml にて、[いま](https://github.com/LayerXcom/anonify/blob/46aa090e08216764234e2cbbfe2b4e795cf58de4/azure-pipelines.yml#L20:L20)とは違う行でkickされる（いまの行は anonify-dev イメージを使っているが、 anonify-dev-pgx イメージが必要なので）

2021-06-04 08:02 UTC, osuketh commented on azure-pipelines.yml
> +  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
イメージあっています！ `example-encrypted-sql-ops-pg.Dockerfile` のファイル自体はテストでは使わないですがアプリケーション動かす上では必要になるのでそのまま残しておいても良きかもですね

2021-06-04 08:04 UTC, osuketh commented on example/encrypted-sql-ops/pg-extension/Cargo.toml
> +codegen-units = 1
> 細かく -p crate名 とかしてclippyやfmtを当てていくことになる（crate追加の際に忘れやすい）のが懸念
同意でっす

2021-06-04 23:23 UTC, laysakura commented on modules/encrypted-sql-ops-enclave/src/plain_types/plain_avg_state.rs
> +    fn test_calculation() {
📝 https://dev.azure.com/osukesudo/Anonify/_build/results?buildId=1933&view=logs&j=da70153e-6e81-59ef-ebe1-a2f10a675270&t=c01c25cd-b635-5a49-1c39-a0cb10c70f76&l=10714
ユニットテストちゃんと走ってること確認

2021-06-05 00:44 UTC, laysakura commented on azure-pipelines.yml
> +  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
- a0152c3 で `example-encrypted-sql-ops-pg.Dockerfile` をユーティリティとして使っていく旨をコメント
- 767d02b で "test-pg-extension.sh のような新設スクリプトからkick。"

2021-06-05 03:36 UTC, laysakura commented
ごめんなさい、CI落ちてたので直してからレビューアサインします...（手元で通ってたから油断した） 🙇

2021-06-05 15:58 UTC, osuketh approved these changes
👍

2021-06-05 20:27 UTC, merged